resource "cozystack_vpn" "gateway" {
  name      = "gateway"
  namespace = "tenant-root"

  host = "vpn.example.com"

  users = {
    alice = { password = "change-me" }
    bob   = {} # password autogenerated
  }
}
