package provider

import (
	"maps"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
)

func clickhouseUsersResourceAttribute() rschema.MapNestedAttribute {
	return rschema.MapNestedAttribute{
		Optional:            true,
		MarkdownDescription: "ClickHouse users keyed by user name.",
		NestedObject: rschema.NestedAttributeObject{
			Attributes: map[string]rschema.Attribute{
				"password": rschema.StringAttribute{
					Optional: true, Computed: true, Sensitive: true,
					MarkdownDescription: "Password for the user (autogenerated when omitted).",
				},
				"readonly": rschema.BoolAttribute{
					Optional: true, Computed: true,
					Default:             booldefault.StaticBool(false),
					MarkdownDescription: "Whether the user has read-only access.",
				},
			},
		},
	}
}

func clickhouseSchema() rschema.Schema {
	attributes := identityResourceAttributes("ClickHouse instance name (`metadata.name`). Immutable.")

	maps.Copy(attributes, map[string]rschema.Attribute{
		attrReplicas: rschema.Int64Attribute{
			Optional: true, Computed: true,
			Default:             int64default.StaticInt64(2),
			MarkdownDescription: "Number of ClickHouse replicas per shard.",
		},
		"shards": rschema.Int64Attribute{
			Optional: true, Computed: true,
			Default:             int64default.StaticInt64(1),
			MarkdownDescription: "Number of ClickHouse shards.",
		},
		attrResources:       resourcesResourceAttribute(),
		attrResourcesPreset: presetAttribute("t1.small"),
		attrSize: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("10Gi"),
			MarkdownDescription: "Persistent volume size for data (quantity, e.g. `10Gi`).",
		},
		attrStorageClass: storageClassAttribute(),
		"log_storage_size": rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("2Gi"),
			MarkdownDescription: "Persistent volume size for logs (quantity, e.g. `2Gi`).",
		},
		"log_ttl": rschema.Int64Attribute{
			Optional: true, Computed: true,
			Default:             int64default.StaticInt64(15),
			MarkdownDescription: "Log retention in days.",
		},
		specBackup: backupResourceAttribute(
			"Backup configuration. Only the system-bucket opt-in is managed here — the per-release S3 " +
				"settings are deprecated upstream in favour of the platform-managed backup class and are " +
				"deliberately left unmanaged. Omitting the block leaves the flag to the server; once an " +
				"instance has opted in, set `use_system_bucket = false` to opt back out, because deleting " +
				"the block keeps the last applied value. Like every unmanaged part of the spec, backup " +
				"fields set outside Terraform are not carried over by an apply.",
		),
		"users": clickhouseUsersResourceAttribute(),
	})
	maps.Copy(attributes, statusResourceAttributes())
	maps.Copy(attributes, waitBehaviorAttributes())

	return rschema.Schema{
		MarkdownDescription: "A Cozystack managed ClickHouse instance, deployed inside a tenant namespace. " +
			"The clickhouseKeeper block uses server defaults.",
		Attributes: attributes,
	}
}

func clickhouseDataSourceSchema() dsschema.Schema {
	attributes := identityDataSourceAttributes("ClickHouse instance name.")

	maps.Copy(attributes, map[string]dsschema.Attribute{
		attrReplicas:        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Number of replicas per shard."},
		"shards":            dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Number of shards."},
		attrResources:       resourcesDataSourceAttribute(),
		attrResourcesPreset: dsschema.StringAttribute{Computed: true, MarkdownDescription: "Sizing preset."},
		attrSize:            dsschema.StringAttribute{Computed: true, MarkdownDescription: "Persistent volume size for data."},
		attrStorageClass:    dsschema.StringAttribute{Computed: true, MarkdownDescription: "StorageClass used to store the data."},
		"log_storage_size":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Persistent volume size for logs."},
		"log_ttl":           dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Log retention in days."},
		specBackup:          backupDataSourceAttribute("Backup configuration, limited to the system-bucket opt-in."),
		"users": dsschema.MapNestedAttribute{
			Computed:            true,
			MarkdownDescription: "ClickHouse users keyed by user name.",
			NestedObject: dsschema.NestedAttributeObject{
				Attributes: map[string]dsschema.Attribute{
					"password": dsschema.StringAttribute{Computed: true, Sensitive: true, MarkdownDescription: "User password."},
					"readonly": dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether the user is read-only."},
				},
			},
		},
	})
	maps.Copy(attributes, statusDataSourceAttributes())

	return dsschema.Schema{
		MarkdownDescription: "Read an existing Cozystack ClickHouse instance by name and namespace.",
		Attributes:          attributes,
	}
}
