package provider

import (
	"maps"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

func mariadbSchema() rschema.Schema {
	attributes := identityResourceAttributes("MariaDB instance name (`metadata.name`). Immutable.")

	maps.Copy(attributes, map[string]rschema.Attribute{
		attrReplicas: rschema.Int64Attribute{
			Optional: true, Computed: true,
			Default:             int64default.StaticInt64(2),
			MarkdownDescription: "Number of MariaDB replicas.",
		},
		attrResources:       resourcesResourceAttribute(),
		attrResourcesPreset: presetAttribute("t1.nano"),
		attrSize: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("10Gi"),
			MarkdownDescription: "Persistent volume size (quantity, e.g. `10Gi`).",
		},
		attrStorageClass: storageClassAttribute(),
		attrExternal:     externalAttribute(),
		attrVersion: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("v11.8"),
			Validators:          []validator.String{stringvalidator.OneOf("v11.8", "v11.4", "v10.11", "v10.6")},
			MarkdownDescription: "MariaDB version (`v11.8`, `v11.4`, `v10.11`, `v10.6`).",
		},
		"users": rschema.MapNestedAttribute{
			Optional:            true,
			MarkdownDescription: "MariaDB users keyed by user name.",
			NestedObject: rschema.NestedAttributeObject{
				Attributes: map[string]rschema.Attribute{
					"max_user_connections": rschema.Int64Attribute{
						Optional: true, Computed: true,
						Default:             int64default.StaticInt64(0),
						MarkdownDescription: "Maximum number of connections for the user.",
					},
					"password": rschema.StringAttribute{
						Optional: true, Computed: true, Sensitive: true,
						MarkdownDescription: "Password for the user (autogenerated when omitted).",
					},
				},
			},
		},
		"databases": rolesMapResourceAttribute("Databases keyed by name, each with admin/readonly user roles."),
	})
	maps.Copy(attributes, statusResourceAttributes())
	maps.Copy(attributes, waitBehaviorAttributes())

	return rschema.Schema{
		MarkdownDescription: "A Cozystack managed MariaDB instance, deployed inside a tenant namespace. " +
			"The deprecated inline backup block is not managed; use the BackupClass / Plan flow instead.",
		Attributes: attributes,
	}
}

func mariadbDataSourceSchema() dsschema.Schema {
	attributes := identityDataSourceAttributes("MariaDB instance name.")

	maps.Copy(attributes, map[string]dsschema.Attribute{
		attrReplicas:        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Number of replicas."},
		attrResources:       resourcesDataSourceAttribute(),
		attrResourcesPreset: dsschema.StringAttribute{Computed: true, MarkdownDescription: "Sizing preset."},
		attrSize:            dsschema.StringAttribute{Computed: true, MarkdownDescription: "Persistent volume size."},
		attrStorageClass:    dsschema.StringAttribute{Computed: true, MarkdownDescription: "StorageClass used to store the data."},
		attrExternal:        dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether external access is enabled."},
		attrVersion:         dsschema.StringAttribute{Computed: true, MarkdownDescription: "MariaDB version."},
		"users": dsschema.MapNestedAttribute{
			Computed:            true,
			MarkdownDescription: "MariaDB users keyed by user name.",
			NestedObject: dsschema.NestedAttributeObject{
				Attributes: map[string]dsschema.Attribute{
					"max_user_connections": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Maximum connections."},
					"password":             dsschema.StringAttribute{Computed: true, Sensitive: true, MarkdownDescription: "User password."},
				},
			},
		},
		"databases": rolesMapDataSourceAttribute("Databases keyed by name."),
	})
	maps.Copy(attributes, statusDataSourceAttributes())

	return dsschema.Schema{
		MarkdownDescription: "Read an existing Cozystack MariaDB instance by name and namespace.",
		Attributes:          attributes,
	}
}
