package provider

import (
	"maps"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func opensearchUsersResourceAttribute() rschema.MapNestedAttribute {
	return rschema.MapNestedAttribute{
		Optional:            true,
		MarkdownDescription: "OpenSearch users keyed by user name.",
		NestedObject: rschema.NestedAttributeObject{
			Attributes: map[string]rschema.Attribute{
				"password": rschema.StringAttribute{
					Optional: true, Computed: true, Sensitive: true,
					MarkdownDescription: "Password for the user (autogenerated when omitted).",
				},
				"roles": rschema.ListAttribute{
					Optional:            true,
					ElementType:         types.StringType,
					MarkdownDescription: "OpenSearch roles assigned to the user.",
				},
			},
		},
	}
}

func opensearchSchema() rschema.Schema {
	attributes := identityResourceAttributes("OpenSearch instance name (`metadata.name`). Immutable.")

	maps.Copy(attributes, map[string]rschema.Attribute{
		attrReplicas: rschema.Int64Attribute{
			Optional: true, Computed: true,
			Default:             int64default.StaticInt64(3),
			MarkdownDescription: "Number of OpenSearch replicas.",
		},
		attrResources:       resourcesResourceAttribute(),
		attrResourcesPreset: presetAttribute("c1.medium"),
		attrSize: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("10Gi"),
			MarkdownDescription: "Persistent volume size (quantity, e.g. `10Gi`).",
		},
		attrStorageClass: storageClassAttribute(),
		attrExternal:     externalAttribute(),
		"topology_spread_policy": rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("soft"),
			Validators:          []validator.String{stringvalidator.OneOf("soft", "hard")},
			MarkdownDescription: "Pod topology spread policy (`soft` or `hard`).",
		},
		attrVersion: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("v2"),
			Validators:          []validator.String{stringvalidator.OneOf("v3", "v2", "v1")},
			MarkdownDescription: "OpenSearch major version (`v3`, `v2`, `v1`).",
		},
		"users": opensearchUsersResourceAttribute(),
	})
	maps.Copy(attributes, statusResourceAttributes())
	maps.Copy(attributes, waitBehaviorAttributes())

	return rschema.Schema{
		MarkdownDescription: "A Cozystack managed OpenSearch instance, deployed inside a tenant namespace. " +
			"The images, nodeRoles, and dashboards blocks use server defaults.",
		Attributes: attributes,
	}
}

func opensearchDataSourceSchema() dsschema.Schema {
	attributes := identityDataSourceAttributes("OpenSearch instance name.")

	maps.Copy(attributes, map[string]dsschema.Attribute{
		attrReplicas:             dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Number of replicas."},
		attrResources:            resourcesDataSourceAttribute(),
		attrResourcesPreset:      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Sizing preset."},
		attrSize:                 dsschema.StringAttribute{Computed: true, MarkdownDescription: "Persistent volume size."},
		attrStorageClass:         dsschema.StringAttribute{Computed: true, MarkdownDescription: "StorageClass used to store the data."},
		attrExternal:             dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether external access is enabled."},
		"topology_spread_policy": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Pod topology spread policy."},
		attrVersion:              dsschema.StringAttribute{Computed: true, MarkdownDescription: "OpenSearch major version."},
		"users": dsschema.MapNestedAttribute{
			Computed:            true,
			MarkdownDescription: "OpenSearch users keyed by user name.",
			NestedObject: dsschema.NestedAttributeObject{
				Attributes: map[string]dsschema.Attribute{
					"password": dsschema.StringAttribute{Computed: true, Sensitive: true, MarkdownDescription: "User password."},
					"roles":    dsschema.ListAttribute{Computed: true, ElementType: types.StringType, MarkdownDescription: "Roles assigned to the user."},
				},
			},
		},
	})
	maps.Copy(attributes, statusDataSourceAttributes())

	return dsschema.Schema{
		MarkdownDescription: "Read an existing Cozystack OpenSearch instance by name and namespace.",
		Attributes:          attributes,
	}
}
