package provider

import (
	"maps"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func pgUsersResourceAttribute() rschema.MapNestedAttribute {
	return rschema.MapNestedAttribute{
		Optional:            true,
		MarkdownDescription: "PostgreSQL users keyed by user name.",
		NestedObject: rschema.NestedAttributeObject{
			Attributes: map[string]rschema.Attribute{
				"password": rschema.StringAttribute{
					Optional: true, Computed: true, Sensitive: true,
					MarkdownDescription: "Password for the user (autogenerated when omitted).",
				},
				"replication": rschema.BoolAttribute{
					Optional: true, Computed: true,
					Default:             booldefault.StaticBool(false),
					MarkdownDescription: "Whether the user has replication privileges.",
				},
			},
		},
	}
}

func pgDatabasesResourceAttribute() rschema.MapNestedAttribute {
	return rschema.MapNestedAttribute{
		Optional:            true,
		MarkdownDescription: "Databases keyed by name.",
		NestedObject: rschema.NestedAttributeObject{
			Attributes: map[string]rschema.Attribute{
				"extensions": rschema.ListAttribute{
					Optional: true, ElementType: types.StringType,
					MarkdownDescription: "Enabled PostgreSQL extensions.",
				},
				"roles": rschema.SingleNestedAttribute{
					Optional:            true,
					MarkdownDescription: "User roles for this database.",
					Attributes: map[string]rschema.Attribute{
						"admin":    rschema.ListAttribute{Optional: true, ElementType: types.StringType, MarkdownDescription: "Users with admin privileges."},
						"readonly": rschema.ListAttribute{Optional: true, ElementType: types.StringType, MarkdownDescription: "Users with read-only privileges."},
					},
				},
			},
		},
	}
}

func postgresSchema() rschema.Schema {
	attributes := identityResourceAttributes("Postgres instance name (`metadata.name`). Immutable.")

	maps.Copy(attributes, map[string]rschema.Attribute{
		attrReplicas: rschema.Int64Attribute{
			Optional: true, Computed: true,
			Default:             int64default.StaticInt64(2),
			MarkdownDescription: "Number of PostgreSQL replicas.",
		},
		attrResources:       resourcesResourceAttribute(),
		attrResourcesPreset: presetAttribute("t1.micro"),
		attrSize: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("10Gi"),
			MarkdownDescription: "Persistent volume size (quantity, e.g. `10Gi`).",
		},
		attrStorageClass: storageClassAttribute(),
		attrExternal:     externalAttribute(),
		attrVersion: rschema.StringAttribute{
			Optional: true, Computed: true,
			Default:             stringdefault.StaticString("v18"),
			Validators:          []validator.String{stringvalidator.OneOf("v18", "v17", "v16", "v15", "v14", "v13")},
			MarkdownDescription: "PostgreSQL major version (`v18`…`v13`).",
		},
		"users":     pgUsersResourceAttribute(),
		"databases": pgDatabasesResourceAttribute(),
	})
	maps.Copy(attributes, statusResourceAttributes())
	maps.Copy(attributes, waitBehaviorAttributes())

	return rschema.Schema{
		MarkdownDescription: "A Cozystack managed PostgreSQL instance, deployed inside a tenant namespace. " +
			"The postgresql tuning, quorum, deprecated backup, and bootstrap blocks use server defaults.",
		Attributes: attributes,
	}
}

func postgresDataSourceSchema() dsschema.Schema {
	attributes := identityDataSourceAttributes("Postgres instance name.")

	rolesDS := dsschema.SingleNestedAttribute{
		Computed:            true,
		MarkdownDescription: "User roles for this database.",
		Attributes: map[string]dsschema.Attribute{
			"admin":    dsschema.ListAttribute{Computed: true, ElementType: types.StringType, MarkdownDescription: "Admin users."},
			"readonly": dsschema.ListAttribute{Computed: true, ElementType: types.StringType, MarkdownDescription: "Read-only users."},
		},
	}

	maps.Copy(attributes, map[string]dsschema.Attribute{
		attrReplicas:        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Number of replicas."},
		attrResources:       resourcesDataSourceAttribute(),
		attrResourcesPreset: dsschema.StringAttribute{Computed: true, MarkdownDescription: "Sizing preset."},
		attrSize:            dsschema.StringAttribute{Computed: true, MarkdownDescription: "Persistent volume size."},
		attrStorageClass:    dsschema.StringAttribute{Computed: true, MarkdownDescription: "StorageClass used to store the data."},
		attrExternal:        dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether external access is enabled."},
		attrVersion:         dsschema.StringAttribute{Computed: true, MarkdownDescription: "PostgreSQL major version."},
		"users": dsschema.MapNestedAttribute{
			Computed:            true,
			MarkdownDescription: "PostgreSQL users keyed by user name.",
			NestedObject: dsschema.NestedAttributeObject{
				Attributes: map[string]dsschema.Attribute{
					"password":    dsschema.StringAttribute{Computed: true, Sensitive: true, MarkdownDescription: "User password."},
					"replication": dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether the user has replication privileges."},
				},
			},
		},
		"databases": dsschema.MapNestedAttribute{
			Computed:            true,
			MarkdownDescription: "Databases keyed by name.",
			NestedObject: dsschema.NestedAttributeObject{
				Attributes: map[string]dsschema.Attribute{
					"extensions": dsschema.ListAttribute{Computed: true, ElementType: types.StringType, MarkdownDescription: "Enabled extensions."},
					"roles":      rolesDS,
				},
			},
		},
	})
	maps.Copy(attributes, statusDataSourceAttributes())

	return dsschema.Schema{
		MarkdownDescription: "Read an existing Cozystack PostgreSQL instance by name and namespace.",
		Attributes:          attributes,
	}
}
