package provider

import (
	"maps"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func vpnSchema() rschema.Schema {
	attributes := identityResourceAttributes("VPN name (`metadata.name`). Immutable.")

	maps.Copy(attributes, map[string]rschema.Attribute{
		attrReplicas: rschema.Int64Attribute{
			Optional:            true,
			Computed:            true,
			Default:             int64default.StaticInt64(2),
			MarkdownDescription: "Number of VPN server replicas.",
		},
		attrResourcesPreset: rschema.StringAttribute{
			Optional:            true,
			Computed:            true,
			Default:             stringdefault.StaticString("t1.nano"),
			MarkdownDescription: "Sizing preset applied when `resources` is omitted.",
		},
		attrResources: resourcesResourceAttribute(),
		attrExternal: rschema.BoolAttribute{
			Optional:            true,
			Computed:            true,
			Default:             booldefault.StaticBool(false),
			MarkdownDescription: "Enable external access from outside the cluster.",
		},
		attrHost: rschema.StringAttribute{
			Optional:            true,
			Computed:            true,
			Default:             stringdefault.StaticString(""),
			MarkdownDescription: "Host used to substitute into generated URLs.",
		},
		"users": rschema.MapNestedAttribute{
			Optional:            true,
			MarkdownDescription: "VPN users keyed by user name.",
			NestedObject: rschema.NestedAttributeObject{
				Attributes: map[string]rschema.Attribute{
					"password": rschema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Sensitive:           true,
						MarkdownDescription: "Password for the user (autogenerated when omitted).",
					},
				},
			},
		},
		"external_ips": rschema.ListAttribute{
			Optional:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "External IPs for the service; defaults to a LoadBalancer when empty.",
		},
	})
	maps.Copy(attributes, statusResourceAttributes())
	maps.Copy(attributes, waitBehaviorAttributes())

	return rschema.Schema{
		MarkdownDescription: "A Cozystack managed VPN server, deployed inside a tenant namespace.",
		Attributes:          attributes,
	}
}

func vpnDataSourceSchema() dsschema.Schema {
	attributes := identityDataSourceAttributes("VPN name.")

	maps.Copy(attributes, map[string]dsschema.Attribute{
		attrReplicas:        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Number of replicas."},
		attrResourcesPreset: dsschema.StringAttribute{Computed: true, MarkdownDescription: "Sizing preset."},
		attrResources:       resourcesDataSourceAttribute(),
		attrExternal:        dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether external access is enabled."},
		attrHost:            dsschema.StringAttribute{Computed: true, MarkdownDescription: "Host used in generated URLs."},
		"users": dsschema.MapNestedAttribute{
			Computed:            true,
			MarkdownDescription: "VPN users keyed by user name.",
			NestedObject: dsschema.NestedAttributeObject{
				Attributes: map[string]dsschema.Attribute{
					"password": dsschema.StringAttribute{Computed: true, Sensitive: true, MarkdownDescription: "User password."},
				},
			},
		},
		"external_ips": dsschema.ListAttribute{Computed: true, ElementType: types.StringType, MarkdownDescription: "External IPs for the service."},
	})
	maps.Copy(attributes, statusDataSourceAttributes())

	return dsschema.Schema{
		MarkdownDescription: "Read an existing Cozystack VPN by name and namespace.",
		Attributes:          attributes,
	}
}
